[project]
name = "zoned-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "eddoyang", email = "eddoyang@students.cs.ubc.ca" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "anthropic>=0.124.0",
    "docling>=2.120.2",
    "openai>=3.3.0",
    "pgvector>=0.5.0",
    "psycopg[binary]>=3.3.4",
    "python-dotenv>=1.2.3",
    "tiktoken>=0.14.0",
]

[project.scripts]
zoned-chatbot = "zoned_chatbot.ask:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.3",
]
